### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by aminebenkeroum** [botmetrics/botmetrics#19]
Hello everyone, 

I'm deploying Botmetrics api on a private server, so I change the API ENV URL, but when I track POST calls I get : 
`Started POST "/bots/68fd2d3060ad/events" for 54.161.121.186 at 2016-09-30 10:31:44 +0000
10:31:44 web.1          | Processing by EventsController#create as JSON
10:31:44 web.1          |   Parameters: {"event"=>"{\"object\":\"page\",\"entry\":[{\"id\":\"145584749232568\",\"time\":1475231503927,\"messaging\":[{\"sender\":{\"id\":\"1158741300867145\"},\"recipient\":{\"id\":\"145584749232568\"},\"timestamp\":0,\"delivery\":{\"mids\":[\"mid.1475231503541:f9d95116dbe82db360\"],\"watermark\":1475231503673,\"seq\":341}}]}]}", "bot_id"=>"68fd2d3060ad"}
10:31:44 web.1          | Can't verify CSRF token authenticity
10:31:44 web.1          | Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)`

**Comment by arunthampi** [comment]
@aminebenkeroum the `"Can't verify CSRF token authenticity"` message that is printed is a warning afaict. Can you double check the `BOTMETRICS_API_KEY` is set correctly in your client? I will investigate further on my side.

**Comment by arunthampi** [comment]
Closing for now since we haven't received any extra information. Feel free to re-open if the issue persists.
