### ISSUE TITLE
Allow Link Tracking

### ISSUE THREAD

**Issue by sandeep** [botmetrics/botmetrics#31]
Currently, botmakers do not have a way to know when links are clicked by users in the chat window. We can provide link click analytics by wrapping the link and redirecting the user.
This will be helpful in understanding user link click conversions. 

Must: 
- [x] Track link + bot_id + user_id (per bot) 
- [x] Use existing event architecture

NIce to Have: 
- [x] Shortened Links

**Comment by arunthampi** [comment]
Closed by https://github.com/botmetrics/botmetrics/pull/72
